version: '3.1'
services:
  backend:
    image: ${BUILD_IMAGE:-sdc-backend-test}
    build: .
    command: ${TEST_COMMAND}
    env_file:
    - env.sdc.tests
    environment:
      APP_FAST_START_MODE: ${APP_FAST_START_MODE}
      FHIRPATH_MAPPING_SERVICE: http://fhirpath_mapping:8090/parse-template
    links:
      - aidbox
    volumes:
      - .:/app
    depends_on:
      aidbox-healthcheck:
        condition:
          service_healthy
      jute:
        condition:
          service_started
      fhirpath_mapping:
        condition:
          service_started
  aidbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - aidbox
    depends_on:
      - aidbox
    healthcheck:
      test: curl --fail http://aidbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  aidbox:
    image: healthsamurai/aidboxone:stable
    depends_on:
      - aidbox-db
    links:
      - "aidbox-db:database"
    env_file:
      - env.aidbox.tests
    environment:
      AIDBOX_LICENSE: ${TESTS_AIDBOX_LICENSE}
    volumes:
      - ./tests_zen_project:/aidbox-project
  aidbox-db:
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
  jute:
    image: bedasoftware/jute-microservice:latest
  fhirpath_mapping:
    image: bedasoftware/fhirpath-extract:main
