{{- if or (eq .Release.Name "sdc-backend-production") (eq .Release.Name "sdc-backend-master") -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}-backup
spec:
  schedule: "0 4,19 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/image: "ae1cabc64"
        spec:
          imagePullSecrets:

          - name: sdc-backup-registry

          volumes:
          - name: gce-key
            secret:
              secretName: {{ template "secretname.backup" . }}
              items:
              - key: GCE_KEY
                path: account.json
          containers:
          - name: {{ .Chart.Name }}-backup

            image: registry.beda.software/sdc/backup:master

            imagePullPolicy: Always
            volumeMounts:
              - name: gce-key
                mountPath: /config
            env:
              - name: POSTGRES_USER
                value: {{ default "postgres" .Values.user | quote }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "secretname" . }}
                    key: PGPASSWORD

              - name: POSTGRES_DATABASE
                value: sdc

              - name: POSTGRES_HOST
                value: {{ template "fullname" . }}
              - name: GCE_KEYFILE
                value: /config/account.json
            envFrom:
              - secretRef:
                  name: {{ template "secretname.backup" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-backup-before-deploy-{{.Release.Revision}}
spec:
  template:
    metadata:
      annotations:
        checksum/image: "ae1cabc64"
    spec:
      imagePullSecrets:

      - name: sdc-backup-registry

      volumes:
      - name: gce-key
        secret:
          secretName: {{ template "secretname.backup" . }}
          items:
          - key: GCE_KEY
            path: account.json
      containers:
      - name: {{ .Chart.Name }}-backup

        image: registry.beda.software/sdc/backup:master

        imagePullPolicy: Always
        volumeMounts:
          - name: gce-key
            mountPath: /config
        env:
          - name: POSTGRES_USER
            value: {{ default "postgres" .Values.user | quote }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "secretname" . }}
                key: PGPASSWORD
          - name: POSTGRES_DATABASE

            value: sdc

          - name: POSTGRES_HOST
            value: {{ template "fullname" . }}
          - name: GCE_KEYFILE
            value: /config/account.json
        envFrom:
          - secretRef:
              name: {{ template "secretname.backup" . }}
      restartPolicy: OnFailure
{{- end -}}

