name: github-actions
on: [push, pull_request]
env:
  BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:master
  CACHE_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
  TESTS_AIDBOX_LICENSE_KEY: ${{ secrets.TESTS_AIDBOX_LICENSE_KEY }}
  TESTS_AIDBOX_LICENSE_ID: ${{ secrets.TESTS_AIDBOX_LICENSE_ID }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged tonistiigi/binfmt --install all
      - run: docker pull ${{ env.CACHE_IMAGE }} || true
      - run: >-
          docker build --cache-from ${{ env.CACHE_IMAGE }} 
          --tag ${{ env.BUILD_IMAGE }} .
      - name: Run tests
        run: ./run_test.sh

  Publish:
    needs: Build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: >-
          docker buildx build --platform linux/arm64,linux/amd64
          --cache-from ${{ env.CACHE_IMAGE }} --push
          --tag ${{ env.BUILD_IMAGE }} --tag ${{ env.CACHE_IMAGE }} .
