name: github-actions
on: [push, pull_request]
jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:master
            CACHE_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
        steps:
            - uses: actions/checkout@v2
            - run: docker pull ${{ env.CACHE_IMAGE }} || true
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - run: >-
                  docker buildx build --push --platform linux/arm64,linux/amd64
                  --cache-from ${{ env.CACHE_IMAGE }}
                  --tag ${{ env.BUILD_IMAGE }} --tag ${{ env.CACHE_IMAGE }} .
  
